import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Pokemon.module.css';
import axios from 'axios';

export default function Pokemon({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>List Pokemon</h1>

        <table className="table-auto w-full mt-5">
          <thead>
            <tr>
              <th className="border px-4 py-2">No</th>
              <th className="border px-4 py-2">Name</th>
              <th className="border px-4 py-2">URL</th>
            </tr>
          </thead>
          <tbody>
            {posts.results.map((pokemon, index) => (
              <tr key={index} className={(index + 1) % 2 === 0 ? 'bg-gray-700' : ''}>
                <td className="border px-4 py-2">{index + 1}</td>
                <td className="border px-4 py-2">{pokemon.name}</td>
                <td className="border px-4 py-2">
                  <a href={pokemon.url} target="_blank">
                    {pokemon.url}
                  </a>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </main>

      <footer className={styles.footer}>
        <a href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app" target="_blank" rel="noopener noreferrer">
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const response = await axios.get('https://pokeapi.co/api/v2/pokemon?limit=100');
  const posts = await response.data;

  return {
    props: {
      posts,
    },
  };
}
